name: 'Custom Github Action'
description: 'takes number and return the squared number'
inputs:
   num:
   requried: true
   default: "1"
   
outputs:
   num_squared:
   value: ${{}}
runs:
   using: 'composite'
   steps: 
     - name: Insatall python
     uses: actions/setup-python@v4
     with:
        python-version: '3.10'
        - name: Install dependencies
        run: pip install -r requirements.txt
        shell:basg
        - name: Pass inputs to shell
        run:
        echo "INPUT_NUM=${{ inputs.num}}" >> $GITHUB_/ENV
        shell: bash
        - name: fetch the number' square
        id: get-square
        run: python src/get_num_square.py
        shell: bash
      
