name: 'Custom Github Action'
description: 'Takes a number and returns the squared number'
inputs:
  num:
    required: true
    default: "1"
outputs:
  num_squared:
    value: ${{ steps.get_square.outputs.num_squared }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pass inputs to shell
      run: echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
      shell: bash
    - name: Fetch the number's square
      id: get_square
      run: |
        python src/get_num_square.py
      shell: |
